# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0ca772662cf4947774550fe9111af58a2db29af58b9c78ea0e9152bc5298e78ed381033f65b46638065515859b7dca0acf101aca49a4f4ca58d9e51ce5d4c240
  BOOKING_API_KEY: "Ff4BrdNohRXrBDGCT6QkQwtt9"


test:
  secret_key_base: d757def9bf4132243b319c449549e071ccf1fb9c74d7da6cf93f0c65408f7d4757cc8208d4d5620ba18421c5c63b0b0a51b68a38c60a1ff449f67bb34969d5c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
